// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/track.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrackService_CreateTrack_FullMethodName  = "/track.TrackService/CreateTrack"
	TrackService_GetTrackByID_FullMethodName = "/track.TrackService/GetTrackByID"
	TrackService_GetAllTracks_FullMethodName = "/track.TrackService/GetAllTracks"
	TrackService_UpdateTrack_FullMethodName  = "/track.TrackService/UpdateTrack"
	TrackService_DeleteTrack_FullMethodName  = "/track.TrackService/DeleteTrack"
)

// TrackServiceClient is the client API for TrackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrackServiceClient interface {
	CreateTrack(ctx context.Context, in *CreateTrackRequest, opts ...grpc.CallOption) (*CreateTrackResponse, error)
	GetTrackByID(ctx context.Context, in *GetTrackByIDRequest, opts ...grpc.CallOption) (*GetTrackByIDResponse, error)
	GetAllTracks(ctx context.Context, in *GetAllTracksRequest, opts ...grpc.CallOption) (*GetAllTracksResponse, error)
	UpdateTrack(ctx context.Context, in *UpdateTrackRequest, opts ...grpc.CallOption) (*UpdateTrackResponse, error)
	DeleteTrack(ctx context.Context, in *DeleteTrackRequest, opts ...grpc.CallOption) (*DeleteTrackResponse, error)
}

type trackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackServiceClient(cc grpc.ClientConnInterface) TrackServiceClient {
	return &trackServiceClient{cc}
}

func (c *trackServiceClient) CreateTrack(ctx context.Context, in *CreateTrackRequest, opts ...grpc.CallOption) (*CreateTrackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTrackResponse)
	err := c.cc.Invoke(ctx, TrackService_CreateTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackServiceClient) GetTrackByID(ctx context.Context, in *GetTrackByIDRequest, opts ...grpc.CallOption) (*GetTrackByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrackByIDResponse)
	err := c.cc.Invoke(ctx, TrackService_GetTrackByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackServiceClient) GetAllTracks(ctx context.Context, in *GetAllTracksRequest, opts ...grpc.CallOption) (*GetAllTracksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllTracksResponse)
	err := c.cc.Invoke(ctx, TrackService_GetAllTracks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackServiceClient) UpdateTrack(ctx context.Context, in *UpdateTrackRequest, opts ...grpc.CallOption) (*UpdateTrackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTrackResponse)
	err := c.cc.Invoke(ctx, TrackService_UpdateTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackServiceClient) DeleteTrack(ctx context.Context, in *DeleteTrackRequest, opts ...grpc.CallOption) (*DeleteTrackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTrackResponse)
	err := c.cc.Invoke(ctx, TrackService_DeleteTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrackServiceServer is the server API for TrackService service.
// All implementations must embed UnimplementedTrackServiceServer
// for forward compatibility.
type TrackServiceServer interface {
	CreateTrack(context.Context, *CreateTrackRequest) (*CreateTrackResponse, error)
	GetTrackByID(context.Context, *GetTrackByIDRequest) (*GetTrackByIDResponse, error)
	GetAllTracks(context.Context, *GetAllTracksRequest) (*GetAllTracksResponse, error)
	UpdateTrack(context.Context, *UpdateTrackRequest) (*UpdateTrackResponse, error)
	DeleteTrack(context.Context, *DeleteTrackRequest) (*DeleteTrackResponse, error)
	mustEmbedUnimplementedTrackServiceServer()
}

// UnimplementedTrackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrackServiceServer struct{}

func (UnimplementedTrackServiceServer) CreateTrack(context.Context, *CreateTrackRequest) (*CreateTrackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrack not implemented")
}
func (UnimplementedTrackServiceServer) GetTrackByID(context.Context, *GetTrackByIDRequest) (*GetTrackByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrackByID not implemented")
}
func (UnimplementedTrackServiceServer) GetAllTracks(context.Context, *GetAllTracksRequest) (*GetAllTracksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTracks not implemented")
}
func (UnimplementedTrackServiceServer) UpdateTrack(context.Context, *UpdateTrackRequest) (*UpdateTrackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTrack not implemented")
}
func (UnimplementedTrackServiceServer) DeleteTrack(context.Context, *DeleteTrackRequest) (*DeleteTrackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTrack not implemented")
}
func (UnimplementedTrackServiceServer) mustEmbedUnimplementedTrackServiceServer() {}
func (UnimplementedTrackServiceServer) testEmbeddedByValue()                      {}

// UnsafeTrackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackServiceServer will
// result in compilation errors.
type UnsafeTrackServiceServer interface {
	mustEmbedUnimplementedTrackServiceServer()
}

func RegisterTrackServiceServer(s grpc.ServiceRegistrar, srv TrackServiceServer) {
	// If the following call pancis, it indicates UnimplementedTrackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrackService_ServiceDesc, srv)
}

func _TrackService_CreateTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServiceServer).CreateTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackService_CreateTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServiceServer).CreateTrack(ctx, req.(*CreateTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackService_GetTrackByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServiceServer).GetTrackByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackService_GetTrackByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServiceServer).GetTrackByID(ctx, req.(*GetTrackByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackService_GetAllTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllTracksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServiceServer).GetAllTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackService_GetAllTracks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServiceServer).GetAllTracks(ctx, req.(*GetAllTracksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackService_UpdateTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServiceServer).UpdateTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackService_UpdateTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServiceServer).UpdateTrack(ctx, req.(*UpdateTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackService_DeleteTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServiceServer).DeleteTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackService_DeleteTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServiceServer).DeleteTrack(ctx, req.(*DeleteTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrackService_ServiceDesc is the grpc.ServiceDesc for TrackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "track.TrackService",
	HandlerType: (*TrackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrack",
			Handler:    _TrackService_CreateTrack_Handler,
		},
		{
			MethodName: "GetTrackByID",
			Handler:    _TrackService_GetTrackByID_Handler,
		},
		{
			MethodName: "GetAllTracks",
			Handler:    _TrackService_GetAllTracks_Handler,
		},
		{
			MethodName: "UpdateTrack",
			Handler:    _TrackService_UpdateTrack_Handler,
		},
		{
			MethodName: "DeleteTrack",
			Handler:    _TrackService_DeleteTrack_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/track.proto",
}
